# Generated by Django 5.2.4 on 2026-03-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0008_department_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='is_accepting_applications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='max_file_size_mb',
            field=models.IntegerField(default=2),
        ),
    ]
