# Generated by Django 4.2.11 on 2026-03-13 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_remove_department_contact_person_and_more'),
        ('adminpanel', '0005_emailtemplate_report_day_alter_emailtemplate_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=150)),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='admin',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department'),
        ),
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'General Admin'), ('dept_admin', 'Department Admin')], default='admin', max_length=20),
        ),
    ]
