# Generated by Django 4.2.11 on 2026-03-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_admin_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
